public class Salmo103 {

	public static void main(String[] args) {
		System.out.println("Bendize_ao SENHOR, ó minh’alma e tudo");
		System.out.println("Que_existe em mim, bendiga,");
		System.out.println("Pois seu nome_é santo. Bendize_ó minh’alma_ao SENHOR.");
		System.out.println("Dos seus benefícios");
		System.out.println("Não te_esqueças de nem um só.");
		System.out.println("É Ele quem perdoa todas as tuas mais vis transgressões.");
		System.out.println("");
		System.out.println("Quem sara de todas as tuas doenças;");
		System.out.println("Tu'a vida da cova salva");
		System.out.println("E_a tua cabeça coroa de graça e_amor.");
		System.out.println("Quem tua velhice");
		System.out.println("Cumula de bens a fartar");
		System.out.println("De sorte que tu'a mocidade como_águia se renovará.");
		System.out.println("");
		System.out.println("Justiça_o SENHOR executa e julga");
		System.out.println("A todos os oprimidos.");
		System.out.println("Ao servo Moisés, seus caminhos Deus manifestou;");
		System.out.println("Seus feitos notáveis");
		System.out.println("Aos Israelitas mostrou.");
		System.out.println("Graci'oso é Deus, paciente, benigno e tem compaixão.");
		System.out.println("");
		System.out.println("P'ra sempre su'a ira_o SENHOR não conserva,");
		System.out.println("Nem censura para sempre;");
		System.out.println("Não tem nos tratado conforme_o nosso transgredir,");
		System.out.println("Nem nos retribui, pois,");
		System.out.println("Conso'ante requer nosso mal.");
		System.out.println("Deus ama_ao que_o teme tal qual sobre_a terra se_alteia o céu.");
		System.out.println("");
		System.out.println("E quanto_o_oriente_e_o_ocidente se distam,");
		System.out.println("Assim Deus, de nós, afasta");
		System.out.println("Os nossos pecados; tal pai que do filho tem dó.");
		System.out.println("Assim, dos que_o temem,");
		System.out.println("Demonstra_o Senhor compaixão.");
		System.out.println("Pois Deus sabe_a nossa_estrutura, conhece que nós somos pó.");
		System.out.println("");
		System.out.println("Os dias do homem comparam-se_à relva,");
		System.out.println("Assim como_a flor do campo,");
		System.out.println("O homem floresce, mas desaparece também.");
		System.out.println("Mas murcha ao vento");
		System.out.println("Que nela soprando está;");
		System.out.println("Daí em diante, não mais se conhece qual é seu lugar.");
		System.out.println("");
		System.out.println("Desde_eternidade à eternidade");
		System.out.println("A misericórdia segue");
		System.out.println("A todos que_o temem; justiça sobre_as gerações;");
		System.out.println("A todos que guardam");
		System.out.println("O pacto firmado por Deus");
		System.out.println("E para_os que lembram dos seus mandamentos e_os cumprem, também.");
		System.out.println("");
		System.out.println("Nos céus, Deus estabeleceu o seu trono;");
		System.out.println("Seu reino domina tudo.");
		System.out.println("E todas as hostes de anjos, a Deus bendizei,");
		System.out.println("Grandiosos em força,");
		System.out.println("Que sua Palavra cumpris,");
		System.out.println("E_às ordens de Deus, todas elas, à risca, sim, executais.");
		System.out.println("");
		System.out.println("E vós os exércitos seus, bendizei ao");
		System.out.println("SENHOR, vós os seus ministros");
		System.out.println("Que sua vontade fazeis, bendizei ao SENHOR.");
		System.out.println("Vós todas as obras,");
		System.out.println("Em todo lugar bendizei;");
		System.out.println("E_em todo domínio de Deus, sim, bendize, ó minh’alma,_ao SENHOR.");
	}
}