public class Salmo10 {

	public static void main(String[] args) {
		System.out.println("Por que SENHOR ficas longe,");
		System.out.println("Te_escondes na provação?");
		System.out.println("Os ímpios com grande_arrogância");
		System.out.println("Ao pobre vem perseguir.");
		System.out.println("Nas próprias tramas que_urdiram");
		System.out.println("Presas, pois, venham ser.");
		System.out.println("Pois, se vangloria_o perverso");
		System.out.println("Da sua cobiça vil.");
		System.out.println("Blasfema_o_avarento contra_o SENHOR");
		System.out.println("e_o maldiz.");
		System.out.println("Não investiga_o perverso, pois");
		System.out.println("Que Deus não existe é seu cogitar,");
		System.out.println("Tem sempre_os caminhos a prosperar,");
		System.out.println("Estão muito longe_os juízos teus.");
		System.out.println("E zomba dos oponentes seus");
		System.out.println("Pois, pra si diz assim:");
		System.out.println("“Abalos nunca jamais terei");
		System.out.println("nas gerações.”");
		System.out.println("");
		System.out.println("Tem ele cheia_a su'a boca");
		System.out.println("De_enganos e maldição,");
		System.out.println("Insulto debaixo da língua,");
		System.out.println("Pecado e transgressão;");
		System.out.println("Monta tocaia nas vilas");
		System.out.println("A fim de espreitar;");
		System.out.println("Trucida inocentes no ermo");
		System.out.println("Qual fera a emboscar.");
		System.out.println("Na rede o pobre já enlaçou,");
		System.out.println("e_o prendeu;");
		System.out.println("Baixa e se_arrasta, e_em seu poder");
		System.out.println("Caíram aflitos. Diz ele_a pensar:");
		System.out.println("“Não lembra_o SENHOR, nem jamais verá,");
		System.out.println("O rosto virou e logo_esqueceu.”");
		System.out.println("Levanta_ó Deus ergue_a tua mão");
		System.out.println("Oh, Senhor, oh, Senhor.");
		System.out.println("Dos pobres não venhas te_esquecer");
		System.out.println("Oh, meu Senhor.");
		System.out.println("");
		System.out.println("Por que razão fica o_ímpio");
		System.out.println("Desprezando ao Senhor,");
		System.out.println("Pensando que Deus não se_importa?");
		System.out.println("Mas tens visto, ó SENHOR.");
		System.out.println("Ao sofrimento atentas");
		System.out.println("Para_os tomar nas mãos;");
		System.out.println("A Ti se entrega o pobre;");
		System.out.println("Do órfão és Defensor.");
		System.out.println("Quebranta o braço do homem mau,");
		System.out.println("Transgressor.");
		System.out.println("Sonda-lhes toda maldade_até");
		System.out.println("Não mais encontrar. Rei eterno_é o SENHOR!");
		System.out.println("Da terra de Deus somem-se_as nações.");
		System.out.println("Dos mansos Tu tens escutado_a voz");
		System.out.println("E firmarás os seus corações;");
		System.out.println("Seu clamor ouvirás;");
		System.out.println("E_assim ninguém lhes trará terror,");
		System.out.println("Pois justo és.");
    }
}